# Generated by Django 4.2.5 on 2023-10-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Titulo', models.CharField(max_length=100)),
                ('Autor', models.CharField(max_length=100)),
                ('Fecha', models.DateField(max_length=10)),
                ('Contenido', models.CharField(max_length=255)),
            ],
        ),
    ]
