# Generated by Django 4.2.5 on 2023-10-06 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScrapeoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='Contenido',
            field=models.TextField(),
        ),
    ]
