# Generated by Django 4.2.5 on 2023-10-12 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScrapeoApp', '0004_news_tag_delete_noticia'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='Tag',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='Author',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='Content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='Date',
            field=models.DateField(max_length=10, null=True),
        ),
    ]
